### ISSUE TITLE
Job not found: build

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [haya14busa/action-workflow_run-status#21]
Getting the following error while using this action:
```
##[error]job not found: build
```

**Comment by haya14busa** [comment]
Please describe more details with reproduction steps.

**Comment by jeizsm** [comment]
I think it's a problem with matrix actions

**Comment by josegonzalez** [comment]
I've also come across this issue in this action run: https://github.com/dokku/ci-docker-image/runs/1496752754?check_suite_focus=true

Here is my worktree at that commit: https://github.com/dokku/ci-docker-image/tree/78e3d5347d05e73c43ef72eb4bc631081f15f897

**Comment by ejntaylor** [comment]
yes also come across a problem with matrix actions - any solutions?
